parameters:
    class_vitmail: AppBundle\Services\VitMail

services:
    vit_user.registration.form.type:
        class: AppBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: vit_user_registration }

    vit_user.RegistrationListener:
        class: AppBundle\EventListener\RegistrationListener
        arguments: [@router, @request_stack]
        tags:
            - { name: kernel.event_subscriber }

    vitmail:
        class:     %class_vitmail%
        arguments: ["@mailer"]

    acme_locale.locale_listener:
            class: AppBundle\EventListener\LocaleListener
            arguments: ["%kernel.default_locale%"]
            tags:
                - { name: kernel.event_subscriber }